name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://ip1029618493.out.azhimalayanvh.com/Firmware/Flyme/16th/9.21.4.24/cn_daily/20210424183733/9c0cb420/update.zip?ali_redirect_domain=download.meizu.com&ali_redirect_ex_ftag=ba57c4c34b52257d0b5624bed68a63daa8ea9f5945ad92de&ali_redirect_ex_tmining_ts=1619440117&ali_redirect_ex_tmining_expire=3600&ali_redirect_ex_hot=100
  ROM_NAME: Flyme
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Cleaning up
         run: |
           docker rmi `docker images -q`

       - name: Cloning ErfanGSIs tools
         run: |
            git clone --recurse-submodules https://github.com/WhiteMouseHuang/ErfanGSIs.git
            sudo chmod -R 777 ErfanGSIs
            curl -sL https://git.io/file-transfer | sh
             
       - name: Setting up Porting Environment
         run: |
           cd ErfanGSIs
           sudo apt update
           sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
           sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME --ab
           ls /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
           7z a -r $ROM_NAME-ab.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/$ROM_NAME-AB-10-*-ErfanGSI.img
           sudo ./transfer wet $ROM_NAME-ab.7z
#           sudo rm $ROM_NAME-ab.7z
#           7z a -r $ROM_NAME-aonly.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/$ROM_NAME-Aonly-*-ErfanGSI.img
#           sudo ./transfer wet $ROM_NAME-aonly.7z
